services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - pipelines
    ports:
      - ${OPEN_WEBUI_PORT-3005}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  pipelines:
    image: ghcr.io/open-webui/pipelines:${PIPELINES_DOCKER_TAG-main}
    container_name: pipeliens
    volumes:
      - pipelines:/app/pipelines
    ports:
      - 9099:9099

volumes:
  open-webui: {}
  pipelines: {}
