services:
  app:
    image: 'vipul20/spliit:latest'
    ports:
      - '3000:3000'
    environment:
      POSTGRES_PRISMA_URL: 'postgresql://postgres:password@db:5432/spliit'
      POSTGRES_URL_NON_POOLING: 'postgresql://postgres:password@db:5432/spliit'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - '5431:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: spliit
      PGDATA: /data/spliit/pgdata
    volumes:
      - '/data/spliit/pgdata:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U postgres'
      interval: 5s
      timeout: 5s
      retries: 5

