name: immich
services:
  immich-server:
    container_name: immich_server
    image: 'ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}'
    volumes:
      - '/mnt/remote_storage/immich/immich-app/data:/usr/src/app/upload'
      - '/mnt/remote_storage/immich/external:/mnt/remote_storage/immich/external:ro'
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - .env
    ports:
      - '7045:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    container_name: immich_machine_learning
    image: 'ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}'
    volumes:
      - 'model-cache:/cache'
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: 'docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792'
    healthcheck:
      test: 'redis-cli ping || exit 1'
    restart: always
  database:
    container_name: immich_postgres
    image: 'docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0'
    environment:
      POSTGRES_PASSWORD: 'super-secret-password'
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - '/mnt/remote_storage/immich/immich-app/postgres:/var/lib/postgresql/data'
    healthcheck:
      test: 'pg_isready --dbname=immich --username=postgres || exit 1; Chksum="$$(psql --dbname=immich --username=postgres --tuples-only --no-align --command=''SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database'')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = ''0'' ] || exit 1'
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      - postgres
      - '-c'
      - shared_preload_libraries=vectors.so
      - '-c'
      - 'search_path="$$user", public, vectors'
      - '-c'
      - logging_collector=on
      - '-c'
      - max_wal_size=2GB
      - '-c'
      - shared_buffers=512MB
      - '-c'
      - wal_compression=on
    restart: always
volumes:
  model-cache: null

